version: '3'
services:
  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: npm
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    volumes:
      - ./config/npm/production.json:/app/config/production.json
      - ./config/npm/config.json:/app/config/default.json
      - ./config/npm/data:/data
      - ./config/npm/letsencrypt:/etc/letsencrypt
    depends_on:
      - pihole
    networks:
      - proxy-network

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '8080:80'
    environment:
      TZ: ${TZ}
      WEBPASSWORD: ${PIHOLE_PASSWORD}
      DNS1: ${DNS1}
      DNS2: ${DNS2}
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      PROXY_LOCATION: 'pihole'
      ServerIP: ${SERVER_IP}
    volumes:
      - './config/pihole/setupVars.conf:/etc/pihole/setupVars.conf'
      - './config/pihole/custom.list:/etc/pihole/custom.list'
      - './config/pihole/dnsmasq.d/02-custom.conf:/etc/dnsmasq.d/02-custom.conf'
      - './config/pihole/pihole-FTL.conf:/etc/pihole/pihole-FTL.conf'
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - NET_ADMIN
    networks:
      - proxy-network

networks:
  proxy-network:
    driver: bridge